CREATE TABLE IF NOT EXISTS  article (
    id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    author TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);